{
 "title": "Benchmarks",
 "time": { "from": "2024-04-06T19:58:28.607Z", "to": "2024-04-06T20:02:37.292Z" },
 "panels": [
  { "title": "Element Interaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Navigate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "browser_navigate_seconds_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Find Element",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "browser_find_seconds_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Click",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "browser_click_seconds_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Enter Text",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "browser_type_seconds_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Time to Click",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(browser_click_seconds_max{framework=\"selenium\", browser=\"chrome\"}[5m])",
     "legendFormat": "Chrome (Selenium)"
    },
    {
     "expr": "avg_over_time(browser_click_seconds_max{framework=\"selenium\", browser=\"chrome_with_managed_service\"}[5m])",
     "legendFormat": "Chrome - Managed Service (Selenium)"
    },
    {
     "expr": "avg_over_time(browser_click_seconds_max{framework=\"selenium\", browser=\"chrome_headless_with_managed_service\"}[5m])",
     "legendFormat": "Headless Chrome - Managed Service (Selenium)"
    },
    {
     "expr": "avg_over_time(browser_click_seconds_max{framework=\"playwright\", browser=\"chrome\"}[5m])",
     "legendFormat": "Chrome (Playwright)"
    }
   ]
  },
  { "title": "Browser Lifecycle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Time to Close Browser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "browser_close_seconds_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time To Open Browser",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "browser_open_seconds_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Time to Open Browser",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(browser_open_seconds_max{framework=\"selenium\", browser=\"chrome\"}[5m])",
     "legendFormat": "Chrome (Selenium)"
    },
    {
     "expr": "avg_over_time(browser_open_seconds_max{framework=\"selenium\", browser=\"chrome_with_managed_service\"}[5m])",
     "legendFormat": "Chrome - Managed Service (Selenium)"
    },
    {
     "expr": "avg_over_time(browser_open_seconds_max{framework=\"selenium\", browser=\"chrome_headless_with_managed_service\"}[5m])",
     "legendFormat": "Headless Chrome - Managed Service (Selenium)"
    },
    {
     "expr": "avg_over_time(browser_open_seconds_max{framework=\"playwright\", browser=\"chrome\"}[5m])",
     "legendFormat": "Chrome (Playwright)"
    }
   ]
  },
  { "title": "Total Test Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Test Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    { "expr": "benchmark_test_seconds_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Test Runtime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(benchmark_test_seconds_max{framework=\"selenium\", browser=\"chrome\"}[5m])",
     "legendFormat": "Chrome (Selenium)"
    },
    {
     "expr": "avg_over_time(benchmark_test_seconds_max{framework=\"selenium\", browser=\"chrome_with_managed_service\"}[5m])",
     "legendFormat": "Chrome - Managed Service (Selenium)"
    },
    {
     "expr": "avg_over_time(benchmark_test_seconds_max{framework=\"selenium\", browser=\"chrome_headless_with_managed_service\"}[5m])",
     "legendFormat": "Chrome Headless - Managed Service (Selenium)"
    },
    {
     "expr": "avg_over_time(benchmark_test_seconds_max{framework=\"playwright\", browser=\"chrome\"}[5m])",
     "legendFormat": "Chrome (Playwright)"
    }
   ]
  }
 ]
}